image: nixos/nix:latest

build:
  before_script:
    - nix-env -iA nixpkgs.bash nixpkgs.nixUnstable nixpkgs.git
    - echo "experimental-features = nix-command flakes ca-references ca-derivations" >> /etc/nix/nix.conf
  script:
    - nix build .#nixosConfigurations.nixpc.config.system.build.toplevel -L
