image: nixos/nix:latest

build:
  before_script:
    - nix-env -iA nixpkgs.bash nixpkgs.nixUnstable nixpkgs.git nixpkgs.cachix
    - cachix authtoken $CACHIX_AUTH_TOKEN
    - cachix use ethancedwards8
    - cachix use nix-community
    - echo "experimental-features = nix-command flakes ca-references ca-derivations" >> /etc/nix/nix.conf
    - nix path-info --all > /tmp/store-path-pre-build
  script:
    - nix build .#nixosConfigurations.nixpc.config.system.build.toplevel -L
  after_script:
    - bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push ethancedwards8"
