#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
xss-lock -- slock &
$HOME/.config/polybar/launch.sh &

if [[ "$HOSTNAME" == *laptop* ]]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

if [[ "$HOSTNAME" == "archpc" ]]; then
	bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
	bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
	bspc monitor DVI-D-0 -d I II III IV V VI VII VIII IX X
	dailyman
fi

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Next state=tiled
bspc rule -a Voxtimer state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacsd state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Chromium
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# dailyman

