name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest, macOS]
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@v15
        with:
          name: ethancedwards8
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build 
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L .nix#{nixvm,usb,archpc,devShell.x86_64-linux,nixrpi}
      - name: Deploy
        run: |
          cachix push ethancedwards8 .nix/result*
