name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Config
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@v15
        with:
          name: ethancedwards8
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: x86_64-linux Build
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L .nix#{nixvm,usb,archpc,devShell.x86_64-linux}

      - name: aarch64 Build
        if: matrix.os == 'ubuntu-24.04-arm'
        run: nix build -L .nix#{nixrpi,devShell.aarch64-linux}

      - name: MacOS Build
        if: matrix.os == 'macos-latest'
        run: nix build -L .nix#{mbair,devShell.aarch64-darwin}

      - name: Deploy
        run: |
          cachix push ethancedwards8 .nix/result*
